### ISSUE TITLE
Sugestão: Alterar title das páginas ao acessar uma sede específica

### ISSUE THREAD

**Issue by RogerEC** [wuerges/maratona-animeitor-rust#12]
Ao acessar a página com os resultados de uma sede específica atualizar o title da página com o nome ou sigla do estado, algo como "Placar completo - Brasil", "Placar completo - Santa Catariana".
Costumo deixar mais de uma aba aberta, uma com o placar geral e de uma sede específica para acompanhar e não precisar ficar recarregando o site, como os titles é sempre o mesmo gera confusão na hora de alternar entre as abas.

P.S.: Iria tentar implementar a alteração, mas eu não conheço nada de Rust. Melhor não me arriscar por hora. 😅

**Comment by wuerges** [comment]
Valeu Roger. É uma mudança fácil de fazer, que vai aumentar bastante a usabilidade.
Você quer ajuda pra tentar mecher no Rust? 
Se tiver a fim, vc mesmo resolve essa issue.

**Comment by RogerEC** [comment]
Irei tentar, aprender novos truques de programação nunca é demais.
Na pior das hipóteses que a Nossa Senhora do Versionamento olhe por nós! 🤣

**Comment by wuerges** [comment]
Firmeza, os principais pontos do projeto a mudar são estes:

View do Timer:

- https://github.com/wuerges/maratona-animeitor-rust/blob/10072537750b93c2f6879563d7f807a3f485526e/lib-seed/src/timer.rs#L49
- https://github.com/wuerges/maratona-animeitor-rust/blob/10072537750b93c2f6879563d7f807a3f485526e/lib-seed/src/views.rs#L187

O problema, que acho que está acontecendo é que o tempo do contest vem em segundos, e o tempo do frozen vem em minutos.
Ao acessar a URL com os dados, a view recebe este json:

```
[ew@kappa maratona-animeitor-rust]$ curl -w '\n' http://localhost:3030/timer
{"current_time":18000,"score_freeze_time":240}
```

**Comment by wuerges** [comment]
Eita, agora que vi que confundi as issues. Essa info ali em cima é pra corrigir o Frozen.

**Comment by wuerges** [comment]
Foi implementado um sistema de configuração usando toml.
Esse arquivo pode ser usado pra definir o título do concurso e o título de cada página.
