### ISSUE TITLE
Banner de frozen exibido durante todo o período da prova

### ISSUE THREAD

**Issue by RogerEC** [wuerges/maratona-animeitor-rust#13]
O placar disponibilizado no site http://animeitor.naquadah.com.br/ exibiu durante todo o período da prova o banner de frozen no cronômetro da competição.
![Antes do frozen](https://user-images.githubusercontent.com/32995553/99157100-03320080-26a5-11eb-8695-06eee76cd4ce.png)
![Após o frozen](https://user-images.githubusercontent.com/32995553/99157122-265cb000-26a5-11eb-958f-44e4e0fe1c6e.png)

**Comment by wuerges** [comment]
Sob análise.

**Comment by wuerges** [comment]
Funcionando.
