### ISSUE TITLE
Runs invertidas?

### ISSUE THREAD

**Issue by ferk6a** [wuerges/maratona-animeitor-rust#9]
Tentei rodar o frozen do aquecimento:

```
$ cargo make build_release
$ cargo run --release --bin simples -p lib-server 3030 lib-server/test/webcast_frozen_aquecimento_1a_fase_2020.zip
```

Para minha surpresa, o placar mostrado foi diferente daquele visto na live. O time "Beto was ejected" foi ejetado pra posição 255 com 149 de penalidade. Porém, ao olhar para as runs, isso não faz sentido, pois o time (teambrpe003), obteve as seguintes runs:

```json
[
  {"id":688691023,"time":7,"team_login":"teambrpe003","prob":"C","answer":{"Yes":7}},
  {"id":689105737,"time":8,"team_login":"teambrpe003","prob":"A","answer":{"Yes":8}},
  {"id":690479227,"time":10,"team_login":"teambrpe003","prob":"C","answer":{"Yes":10}},
  {"id":694939637,"time":18,"team_login":"teambrpe003","prob":"B","answer":{"Yes":18}},
  {"id":695613704,"time":19,"team_login":"teambrpe003","prob":"A","answer":{"Yes":19}},
  {"id":698066920,"time":23,"team_login":"teambrpe003","prob":"A","answer":"No"},
  {"id":698607574,"time":24,"team_login":"teambrpe003","prob":"A","answer":"No"},
  {"id":699550471,"time":25,"team_login":"teambrpe003","prob":"A","answer":"No"},
  {"id":703890710,"time":33,"team_login":"teambrpe003","prob":"A","answer":"No"},
  {"id":720067186,"time":60,"team_login":"teambrpe003","prob":"A","answer":"No"},
  {"id":720976174,"time":61,"team_login":"teambrpe003","prob":"A","answer":{"Yes":61}},
  {"id":722313053,"time":63,"team_login":"teambrpe003","prob":"A","answer":"No"},
  {"id":723905358,"time":66,"team_login":"teambrpe003","prob":"A","answer":"No"},
  {"id":724374484,"time":67,"team_login":"teambrpe003","prob":"A","answer":"No"}
]
```

E o placar reporta A: 61+3, B: 18+0, C: 10+0. O único jeito disso acontecer é as runs terem sido lidas invertidas.

**Comment by wuerges** [comment]
Cara, muito obrigado por avisar.

Sim, os runs estavam invertidos. 
O painel da esquerda usa elas na ordem da mais recente para a menos recente, já o cálculo do placar precisa delas em ordem.

Estou corrigindo o problema.

**Comment by wuerges** [comment]
Ok, o problema foi resolvido. 
A partir de agora, as Runs são armazenadas sempre em ordem crescente no tempo (da mais antiga para mais nova). 
O painel de que mostra as runs agora inverte a ordem das runs antes de mostrar.

Isso agora é garantido desta maneira:

- A única função que pode alterar as runs é a função de inicialização da lista de runs. Esta função ordena as runs.
- As outras funções são somente de leitura.

fcf31420cafcd4174f9b60abdf90028304d4d436
